### ISSUE TITLE
Ubuntu Server: Apache has been updated to 2.4.52 from 2.4.48. ~ Django 3.2.12

### ISSUE THREAD

**Issue by sukso96100** [ubuntu-kr/blog.ubuntu-kr.org#34]
아래 부분을 번역 해 주세요.
https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L277-L324

**Comment by sukso96100** [comment]
@HaeyoonJo

**Comment by HaeyoonJo** [comment]
감사합니다.
