### ISSUE TITLE
Ubuntu 22.04 LTS 릴리스 노트 번역

### ISSUE THREAD

**Issue by sukso96100** [ubuntu-kr/blog.ubuntu-kr.org#7]
- 원문: https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668
- 한국어 번역 초안: https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/jammy-release-note/content/post/jamme-jellyfish-release-notes/index.md

이번에 출시 한 Ubuntu 22.04 LTS 의 릴리스 노트를 한국어로 번역 하고자 하니 많은 참여 바랍니다. LTS 릴리스 이니 만큼, 분량이 많아 많은 분들의 도움이 필요합니다.

## 번역 제출 마감일

2022년 5월 26일 - 일찍 제출 해 주시면 검토 할 시간이 많이 좋으며, 시간이 부족하다 판단되면 연장 될 수도 있습니다.

## 검토자
- @minwook-shin 
- @sigmadream 
- @sukso96100 
- @onting 

## 번역 참여 시 규칙 및 당부사항
- [우분투 한국어 번역팀의 규정에 따라 번역 해 주세요.](https://wiki.ubuntu.com/UbuntuKoreanTranslators)
- [우분투 행동강령을 준수해 주세요.](https://ubuntu.com/community/code-of-conduct)
- 본인이 담당한 부분만 번역 해 주세요.

## 번역 참여 방법
- 아래 단락 목록 중 번역 하고 싶은 부분을 선택하여 본 이슈에 커멘트를 달아주세요. (체크박스 체크 하거나 하진 말아주세요)
- 검토자 분이 확인 후 번역 하실 부분을 할당 해 드립니다. 
- 번역 하실 부분이 정해지면, 본 저장소를 Fork 하신 후,  [`jammy-release-note` 브랜치에 있는 본문 `index.md` 파일](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/jammy-release-note/content/post/jamme-jellyfish-release-notes/index.md)에서 해당 부분을 번역하여 커밋 합니다.
- 번역을 완료 하였다면, 본 저장소에 Pull Request 를 열어 주세요. `jammy-release-note` 브랜치를 대상으로 하여 열어 주시면 됩니다.
- 검토자 분의 검토 후 수정 요청을 받으신 경우, 요청된 부분을 수정하여 추가로 커밋 해 주세요.
- 검토 완료 후, 이상이 없으면 Pull Request 가 승인 및 병합되고, 번역이 반영 됩니다. 

## 번역 관련 논의
- 번역 관련 사소한 질문 등을 채팅으로 논의하는 경우, Slack ubuntu-kr.slack `#0004-l10n` 또는 Matrix `#ubuntu-l10n-ko` 를 이용해 주세요. [(자세한 정보 보려면 클릭)](https://ubuntu-kr.org/chat/)
- 메일링 이용시 [Ubuntu-l10n-ko 메일링 리스트](https://lists.ubuntu.com/mailman/listinfo/Ubuntu-l10n-ko)를 이용하시면 됩니다. 

## 참고
- 번역이 완료되면, 우선 우분투한국커뮤니티 블로그에 게시되며, 추후 우분투한국커뮤니티 위키 신규 구축이 완료되면 위키로 문서를 옮길 예정입니다.

## 번역 부분

- [x] #8 @onting 
- [x] #9 @onting 
- [x] #13 @sukso96100 
- [x] #16 @sigmadream
- [x] #17 @sigmadream
- [x] #18 @sigmadream
- [x] #34 @HaeyoonJo
- [x] #44 @neeks76
- [x] #30 @neeks76
- [x] #14 @GiyeonBang
- [x] #15 @GiyeonBang
- [x] #40 @neeks76
- [x] #20 @ujuc
- [x] #21 @ujuc
- [x] #10 @onting 
- [x] #11 @onting 
- [x] #12 @onting 
- [x] #22 @ujuc
- [x] #23 @ujuc
- [x] #26 @QuqqU

**Comment by onting** [comment]
해당 부분 번역해보겠습니다.

**Comment by sukso96100** [comment]
> 테스크 리스트는 처음 써봐서 불필요하게 수정을 많이 했네요... 체크한 부분 제가 해도 될까요?

네 작업 할당 해 드렸습니다 :)

**Comment by sukso96100** [comment]
[Ubuntu Desktop](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L125-L162) 부분은 제가 번역 하도록 하겠습니다.

**Comment by sukso96100** [comment]
> virtualization 2개 파트 번역을 하고 싶습니다.

아래 두 파트 맞으실까요?
https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L374-L404
https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L406-L440

**Comment by GiyeonBang** [comment]
네, 맞습니다!

**Comment by sukso96100** [comment]
> 네, 맞습니다!

네 번역 진행 해 주시면 됩니다. :)

**Comment by sigmadream** [comment]
#16, #17, #18 은 제가 번역하도록 하겠습니다.

**Comment by ujuc** [comment]
[Ubuntu Server: Ubuntu Server Main Promotions ~ Ceph](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L479-L504) 

[Ubuntu Server: OpenStack ~ needrestart and unattended operations](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L506-L538)

[Known Issues: Linux kernel ~ Ubuntu Server](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L619-L653)

[Known Issues: Platforms ~ s390x](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L655-L679)

해당 부분 참여할께요. 

밑에꺼 볼려고 했더니 얼마없네요..;;

**Comment by sukso96100** [comment]
> [Ubuntu Server: Ubuntu Server Main Promotions ~ Ceph](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L479-L504) 
> 
> [Ubuntu Server: OpenStack ~ needrestart and unattended operations](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L506-L538)
> 
> [Known Issues: Linux kernel ~ Ubuntu Server](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L619-L653)
> 
> [Known Issues: Platforms ~ s390x](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L655-L679)
> 
> 해당 부분 참여할께요. 
> 
> 밑에꺼 볼려고 했더니 얼마없네요..;;

감사합니다 :) 번역 시작 해 주시면 됩니다.

**Comment by QuqqU** [comment]
[Official flavours ~ More about Ubuntu](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L681-L711)

해당 부분 참여할 수 있을까요?

**Comment by sukso96100** [comment]
> QuqqU

네, 번역 해서 제출 해 주시면 되겠습니다.

**Comment by sukso96100** [comment]
> [Ubuntu Server: Quagga replaced with frr ~ Chrony time synchronization](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L360-L372)
> 
> 이렇게 참여 하는건가요? 위 부분 참여할 수 있을까요?

본 이슈의 본문에 "번역 참여 방법" 부분을 먼저 확인하시기 바랍니다.

**Comment by neeks76** [comment]
> > [Ubuntu Server: Quagga replaced with frr ~ Chrony time synchronization](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L360-L372)
> 
> > 
> 
> > 이렇게 참여 하는건가요? 위 부분 참여할 수 있을까요?
> 
> 
> 
> 본 이슈의 본문에 "번역 참여 방법" 부분을 먼저 확인하시기 바랍니다.

1. 아래 단락 목록 중 번역 하고 싶은 부분을 선택하여 본 이슈에 커멘트를 달아주세요. (체크박스 체크 하거나 하진 말아주세요)
2. 검토자 분이 확인 후 번역 하실 부분을 할당 해 드립니다.
3. 번역 하실 부분이 정해지면, 본 저장소를 Fork 하신 후, jammy-release-note 브랜치에 있는 본문 index.md 파일에서 해당 부분을 번역하여 커밋 합니다.

저기, 제가 잘 몰라서요.
저는 지금 1번단계여서 frr과 chrony를 선정하려 커멘트 달았어요. 
그런데, 번역 참여 방법을 확인하라고 한건가요?

이렇게 확인하면 되는건가요?

제가 이쪽 문화를 배우고 있으니 살펴 주셔요. OTL~

**Comment by sukso96100** [comment]
> [Ubuntu Server: Apache has been updated to 2.4.52 from 2.4.48. ~ Django 3.2.12](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L277-L324) 부분 가능할까요?

가능합니다. 할당 해 드렸으니, 번역 시작 하시면 되겠습니다.

**Comment by sukso96100** [comment]
> [Ubuntu Server: Squid ~ ubuntu-advantage-tools](https://github.com/ubuntu-kr/blog.ubuntu-kr.org/blob/5769166b91b07442282aa172308fad71bf401fff/content/post/jamme-jellyfish-release-notes/index.md?plain=1#L442-L478)
> 
> 이부분은 가능할까요?

네 번역 시작 해 주세요

**Comment by neeks76** [comment]
MySQL 8.0 ~ Samba server

이부분 번역 가능할까요? ^^

**Comment by sukso96100** [comment]
> MySQL 8.0 ~ Samba server
> 
> 이부분 번역 가능할까요? ^^

할당 해 드렸습니다

**Comment by sukso96100** [comment]
다음 주 목요일 번역 마감입니다. 늦기 않게 번역을 제출 해 주세요.
@ujuc @GiyeonBang @onting @HaeyoonJo

**Comment by HaeyoonJo** [comment]
> > MySQL 8.0 ~ Samba server
> > 이부분 번역 가능할까요? ^^
> 
> 할당 해 드렸습니다

이번주 목요일까지 마무리하겠습니다.

**Comment by HaeyoonJo** [comment]
> 다음 주 목요일(26일) 번역 마감입니다. 늦기 않게 번역을 제출 해 주세요.
> @ujuc @GiyeonBang @onting @HaeyoonJo

이번주 목요일(19일)까지 마무리하겠습니다

**Comment by sukso96100** [comment]
2일 후 번역 제출 마감 입니다.

**Comment by sukso96100** [comment]
번역 검토에 참여하시는 @minwook-shin @sigmadream @onting 님도 PR 들어오면 검토 부탁드려요.

**Comment by onting** [comment]
네 알겠습니다

**Comment by sukso96100** [comment]
번역에 참여해 주신 분들 모두 수고하셨습니다 :) 제출된 PR 모두 병합 되었고, 최종 검토 후 몇일 안에 배포될 예정입니다.

**Comment by sukso96100** [comment]
번역 배포가 완료 되었습니다. 참여해 주신 모든 분들께 감사 드립니다. 이후 번역에 오류가 있거나 원문에 변동이 있어 업데이트가 필요한 경우, 별도의 이슈를 열어 주시기 바랍니다.
https://blog.ubuntu-kr.org/2022/04/22/jamme-jellyfish-release-notes/
